### ISSUE TITLE
how to get the datasets of MLR-Market-1501, MLR-CUHK03, MLR-VIPeR, MLR-DukeMTMC-reID, and CAVIAR?

### ISSUE THREAD

**Issue by woocoder** [NUISTGY/Deep-High-Resolution-Representation-Learning-for-Cross-Resolution-Person-Re-identification#4]
I can't find the downlinks or the process code of transformation.

**Comment by NUISTGY** [comment]
通过百度网盘分享的文件：MLR-reID...
链接：https://pan.baidu.com/s/1DKqDCil0VTaS_eCCSbOaQw?pwd=3ajt 
提取码：3ajt 
复制这段内容打开「百度网盘APP 即可获取」

**Comment by puyiwen** [comment]
> 通过百度网盘分享的文件：MLR-reID... 链接：https://pan.baidu.com/s/1DKqDCil0VTaS_eCCSbOaQw?pwd=3ajt 提取码：3ajt 复制这段内容打开「百度网盘APP 即可获取」

您好，链接失效了，还能再提供一下吗？非常感谢您~
